addr: 127.0.0.1:8080
hostName: auth.weberc2.com
baseURL: http://127.0.0.1:8080/
issuer: weberc2.com
audience: "*.weberc2.com"
accessSigningKey: |
  -----BEGIN PRIVATE KEY-----
  MIHcAgEBBEIAZPFBLS7kA9XMSgJUNO1OiTiwa1dZoCEBZ6M3ioNWC53FdcvnYuW1
  bk8aAMD/HI8sIgsXmZeucct84OziSJmh452gBwYFK4EEACOhgYkDgYYABAEZnAWh
  i+fgr7z0pwjeyo7tqKR40Wo+EiZfn4X3FIgamqoowH+ERTyYrjDdB3QMU6iOSlDh
  UL9IsM92+ZQbiV0sbwG2MVbDyO7CBHDvoBTa2raZlScjrJe6V4h2dsGmCi2xDOQt
  UueLAXD4CKTdEgz8S0/pW4czm6OYPRgfvLqG7pGjxw==
  -----END PRIVATE KEY-----
refreshSigningKey: |
  -----BEGIN PRIVATE KEY-----
  MIHcAgEBBEIBX5gvx0ig29F7Om7iQEblxVCE4tq2uUY7Dtke0rEoKbg4LqKSAbES
  GNMBpQT2mZn+eavkyqGXjw0bYEW7TYZp64+gBwYFK4EEACOhgYkDgYYABAHsWi7p
  TGnIunsqjRfILPA7ni4d1dKH5U2pKSpSJzAUpQIP9qcf1LJBz2oeaaiXstogKLKd
  BhmPaTs8IgNJC5ICnAAAdUYUlv3xqd0lRTM3M0Sk5i07D7aAz2Gzoi2PRsT3Ae2O
  2dI7HpYTKsP8RqaZp46hoBgcw88rIwhep/L3u4UJhg==
  -----END PRIVATE KEY-----
resetSigningKey: |
  -----BEGIN PRIVATE KEY-----
  MIHcAgEBBEIAJ49681/ZpFQvgMPiJRJn0z+rL9SEGSg+9BSzR1wCs4Eun1armRz1
  wmhjshce1oexdJuQyw9CMNQ+sz0cddYUPRigBwYFK4EEACOhgYkDgYYABABzK8Sh
  GR4aQLVY41cQgKEgkROy7pi0NMHRZQdFkD9H7QpztQdLbSVS1YVVHHkq5dao2LgZ
  QUUyrBfxkzKNYfc4BQHAwYJ1B73r5ZvMwtcSVs/Nc+rVX3O/nw27VQ7lmAREseFH
  Alsx4HqycEOu+23QmucQBeSdGFlsz5wgpLUBCjxKmw==
  -----END PRIVATE KEY-----
notificationSender: auth@weberc2.com
defaultRedirectLocation: https://blog.weberc2.com
redirectDomain: weberc2.com
