apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.iam.aws.weberc2.com
spec:
  group: iam.aws.weberc2.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            userName:
              type: string
              pattern: "^[A-z0-9_+=,.@-]+$"
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User