apiVersion: v1
kind: Namespace
metadata:
  name: aws-system

---
apiVersion: v1
kind: Secret
metadata:
  namespace: aws-system
  name: user-controller-credentials
# stringData:
#   update manually
#   AWS_ACCESS_KEY_ID: ""
#   AWS_SECRET_ACCESS_KEY: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aws-system
  name: user-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-controller
  template:
    metadata:
      labels:
        app: user-controller
    spec:
      serviceAccountName: user-controller
      containers:
      - name: user-controller
        image: aws-user-controller
        imagePullPolicy: IfNotPresent
        command: ["/app"]
        envFrom:
        - secretRef:
            name: user-controller-credentials
        env:
        - name: AWS_REGION
          value: us-east-2
        ports:
        - name: http-port
          containerPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-controller
  namespace: aws-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-controller
  namespace: aws-system
rules:
- apiGroups: ["iam.aws.weberc2.com"]
  resources: ["users"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-controller
  namespace: aws-system
subjects:
- kind: ServiceAccount
  name: user-controller
  namespace: aws-system
roleRef:
  kind: ClusterRole
  name: user-controller
  apiGroup: rbac.authorization.k8s.io